import './globals.css';

import React from 'react';

import { AppNav } from '@/components/app-nav';

import { Providers } from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className="debug-screens">
          <main className="flex min-h-screen flex-col items-center">
            <AppNav />
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
